version: '3.3'
services:
    demo-app:
        build: .
        command: /start-reload.sh
        environment:
            TZ: 'Asia/Tokyo'
            PYTHONDONTWRITEBYTECODE: 1
        volumes:
            - .:/app
        ports:
            - 8000:80

    db:
        image: mysql:8.0
        environment:
            TZ: 'Asia/Tokyo'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'demo'
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
